application/views.py
# from .models import *
from .models import Movie, Show, Theater, User, Admin, Booking_movies, Booking_show, Booking_venue, Base
from flask import Blueprint, jsonify
from flask import Flask, render_template, request, redirect, flash, session, url_for
from sqlalchemy import select
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
import datetime

bp = Blueprint('views', __name__)
engine = create_engine("sqlite:///./ticket_show.db")


@bp.route('/')
def Index():
  if "email" in session:
    with Session(engine) as ses:
      movie_rows = ses.query(Movie).order_by(
        Movie.rating.desc()).limit(4).all()
      show_rows = ses.query(Show).order_by(Show.rating.desc()).limit(4).all()
      movie_rows_rec = ses.query(Movie).order_by(
        Movie.rating.desc()).limit(2).all()
      show_rows_rec = ses.query(Show).order_by(
        Show.rating.desc()).limit(2).all()

    return render_template('index.html',
                           movie_rows=movie_rows,
                           show_rows=show_rows,
                           movie_rows_rec=movie_rows_rec,
                           show_rows_rec=show_rows_rec,
                           status='logged')
  else:
    with Session(engine) as ses:
      movie_rows = ses.query(Movie).order_by(
        Movie.rating.desc()).limit(4).all()
      show_rows = ses.query(Show).order_by(Show.rating.desc()).limit(4).all()
      movie_rows_rec = ses.query(Movie).order_by(
        Movie.rating.desc()).limit(2).all()
      show_rows_rec = ses.query(Show).order_by(
        Show.rating.desc()).limit(2).all()

    return render_template('index.html',
                           movie_rows=movie_rows,
                           show_rows=show_rows,
                           movie_rows_rec=movie_rows_rec,
                           show_rows_rec=show_rows_rec)


@bp.route('/movies', methods=['GET', 'POST'])
def movies():
  headers = request.headers
  if headers.get('flag') == 'json':
    with Session(engine) as ses:
      rows = ses.query(Movie).all()
    movies = [row.__dict__ for row in rows]
    for movie in movies:
      movie.pop('_sa_instance_state', None)
    # Return the JSON response
    return jsonify(movies)
  if request.headers.get(
      'User-Agent'
  ) != 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36':
    # Return an error response for curl requests
    return "Curl requests are not allowed without headers.", 400

  if "email" in session:
    if request.method == 'POST':
      # print('inside post')
      category = request.form.get('tag')
      # print(category)
      city = request.form.get('city')
      # print(city)
      rating = request.form.get('sort_by_rating')
      # print(type(category),type(city),type(rating))
      if category == "None" and city == None and rating == None:
        with Session(engine) as ses:
          rows = ses.query(Movie).all()
          cities = ses.query(Theater).all()
          return render_template('movies.html',
                                 movies=rows,
                                 status='logged',
                                 cities=cities)

      else:
        with Session(engine) as ses:
          rows = ses.query(Movie).all()

          if category != None:
            filtered_rows = []
            for row in rows:
              if row.tags == category:
                filtered_rows.append(row)
            rows = []
            rows = filtered_rows
          if rating != None:
            rows = ses.query(Movie).order_by(Movie.rating.desc()).all()

          cities = ses.query(Theater).all()
          return render_template('movies.html',
                                 movies=rows,
                                 status='logged',
                                 cities=cities)
    else:
      with Session(engine) as ses:
        rows = ses.query(Movie).all()
        cities = ses.query(Theater).all()
        # print('sdsd')
        # print(cities)
        return render_template('movies.html',
                               movies=rows,
                               status='logged',
                               cities=cities)
  else:
    if request.method == 'POST':
      print('inside post')
      category = request.form.get('tag')
      print(category)
      city = request.form.get('city')
      print(city)
      rating = request.form.get('sort_by_rating')
      print(type(category), type(city), type(rating))
      if category == "None" and city == None and rating == None:
        with Session(engine) as ses:
          rows = ses.query(Movie).all()
          cities = ses.query(Theater).all()
          return render_template('movies.html', movies=rows, cities=cities)

      else:
        with Session(engine) as ses:
          rows = ses.query(Movie).all()

          if category != None:
            filtered_rows = []
            for row in rows:
              if row.tags == category:
                filtered_rows.append(row)
            rows = []
            rows = filtered_rows
          if rating != None:
            rows = ses.query(Movie).order_by(Movie.rating.desc()).all()

          cities = ses.query(Theater).all()
          return render_template('movies.html', movies=rows, cities=cities)
    else:
      with Session(engine) as ses:
        rows = ses.query(Movie).all()
        cities = ses.query(Theater).all()
        # print('sdsd')
        # print(cities)
        return render_template('movies.html', movies=rows, cities=cities)


@bp.route('/shows', methods=['GET', 'POST'])
def shows():
  headers = request.headers
  # print(headers)
  if headers.get('flag') == 'json':
    with Session(engine) as ses:
      rows = ses.query(Show).all()
    shows = [row.__dict__ for row in rows]
    for show in shows:
      show.pop('_sa_instance_state', None)
    # Return the JSON response
    return jsonify(shows)
  if request.headers.get(
      'User-Agent'
  ) != 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36':
    # Return an error response for curl requests
    return "Curl requests are not allowed without headers.", 400
  if "email" in session:
    if request.method == 'POST':
      category = request.form.get('tag')
      rating = request.form.get('sort_by_rating')
      if category == "None" and rating == None:
        with Session(engine) as ses:
          rows = ses.query(Show).all()
          return render_template(
            'shows.html',
            shows=rows,
            status='logged',
          )
      else:
        with Session(engine) as ses:
          rows = ses.query(Show).all()
          if category != "None":
            filtered_rows = []
            for row in rows:
              if row.tags == category:
                filtered_rows.append(row)
            rows = []
            rows = filtered_rows
          if rating != None:
            rows = ses.query(Show).order_by(Show.rating.desc()).all()
          return render_template(
            'shows.html',
            shows=rows,
            status='logged',
          )
    else:
      with Session(engine) as ses:
        rows = ses.query(Show).all()
        return render_template('shows.html', shows=rows, status='logged')
  else:
    if request.method == 'POST':
      print('inside post')
      category = request.form.get('tag')
      rating = request.form.get('sort_by_rating')
      # print(type(category),type(city),type(rating))
      if category == "None" and rating == None:
        with Session(engine) as ses:
          rows = ses.query(Show).all()
          return render_template(
            'shows.html',
            shows=rows,
          )
      else:
        with Session(engine) as ses:
          rows = ses.query(Show).all()
          if category != "None":
            filtered_rows = []
            for row in rows:
              if row.tags == category:
                filtered_rows.append(row)
            rows = []
            rows = filtered_rows
          if rating != None:
            rows = ses.query(Show).order_by(Show.rating.desc()).all()
          return render_template('shows.html', shows=rows)
    else:
      with Session(engine) as ses:
        rows = ses.query(Show).all()
        return render_template(
          'shows.html',
          shows=rows,
        )


########################################
@bp.route('/venues', methods=['GET', 'POST'])
def venues():
  headers = request.headers
  if headers.get('flag') == 'json':
    with Session(engine) as ses:
      rows = ses.query(Theater).all()
    theaters = [row.__dict__ for row in rows]
    for theater in theaters:
      theater.pop('_sa_instance_state', None)
    # Return the JSON response
    return jsonify(theaters)
  if request.headers.get(
      'User-Agent'
  ) != 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36':
    # Return an error response for curl requests
    return "Curl requests are not allowed without headers.", 400
  if "email" in session:
    if request.method == 'POST':
      city = request.form.get('tag')
      rating = request.form.get('sort_by_rating')
      if city == "None" and rating == None:
        with Session(engine) as ses:
          rows = ses.query(Theater).all()
          return render_template(
            'venues.html',
            venues=rows,
            status='logged',
          )
      else:
        with Session(engine) as ses:
          rows = ses.query(Theater).all()
          if city != "None":
            filtered_rows = []
            for row in rows:
              if row.place == city:

application/templates/add_movie.html
{% extends 'base.html' %} {% block head %} {% endblock %} {% block body %}
<div class="container mt-5">
  <div class="container">
    <div class="row">
      <a href="{{url_for('views.movie_management')}}" class="col-md-4 mb-4">
        <button type="button" class="btn btn-dark" style="width: 200px">
          Movie Management
        </button>
      </a>
      <a href="{{url_for('views.show_management')}}" class="col-md-4 mb-4">
        <button type="button" class="btn btn-dark" style="width: 200px">
          Show Management
        </button>
      </a>
      <a href="{{url_for('views.venue_management')}}" class="col-md-4 mb-4">
        <button type="button" class="btn btn-dark" style="width: 200px">
          Venue Management
        </button>
      </a>
    </div>
    <div class="row">
      <a href="{{url_for('views.add_movie')}}" class="col-md-4 mb-4">
      <button
        type="button"
        class="btn btn-dark"
        style="width: 200px"
      >
        Add New Movie
      </button>
    </a>
    <a href="{{url_for('views.add_show')}}" class="col-md-4 mb-4">
      <button
        type="button"
        class="btn btn-dark"
        style="width: 200px"
      >
        Add New Show
      </button>
    </a>
    <a href="{{url_for('views.add_venue')}}" class="col-md-4 mb-4">
      <button
        type="button"
        class="btn btn-dark"
        style="width: 200px"
      >
        Add New Venue
      </button>
    </a>
      </div>
    </div>
    <h1>Add Movie</h1>
    <form method="POST" action="/admin/add_movie" enctype="multipart/form-data">
      <div class="form-group">
        <label for="name">Name:</label>
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          required
        />
      </div>
      <div class="form-group">
        <label for="desc">Description:</label>
        <textarea
          class="form-control"
          id="desc"
          name="desc"
          rows="3"
          required
        ></textarea>
      </div>
      <div class="form-group">
        <label for="desc">Genre:</label>
        <input
          type="text"
          class="form-control"
          id="tags"
          name="tags"
          required
        />
      </div>
      <div class="form-group">
        <label for="rating">Rating:</label>
        <input
          type="number"
          class="form-control"
          id="rating"
          name="rating"
          min="1"
          max="10"
        />
      </div>
      <div class="form-group">
        <label for="date">Release Date:</label>
        <input
          type="date"
          class="form-control"
          id="date"
          name="date"
          required
        />
      </div>
      <div class="form-group">
        <label for="theaters">Theaters:</label>
        <select class="form-control" id="theaters" name="theaters" multiple>
          {% for theater in theaters %}
          <option value="{{ theater.id }}">
            {{ theater.name }}, {{theater.place}}
          </option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
      <label for="image">Add Image:</label>
      <input type="file" class="form-control" name="file" />
    </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
  {% endblock %}
</div>

application/templates/add_venue.html
{% extends 'base.html' %} {% block body %}
<div class="container mt-5">
  <div class="container">
    <div class="row">
      <a href="{{url_for('views.movie_management')}}" class="col-md-4 mb-4">
        <button type="button" class="btn btn-dark" style="width: 200px">
          Movie Management
        </button>
      </a>
      <a href="{{url_for('views.show_management')}}" class="col-md-4 mb-4">
        <button type="button" class="btn btn-dark" style="width: 200px">
          Show Management
        </button>
      </a>
      <a href="{{url_for('views.venue_management')}}" class="col-md-4 mb-4">
        <button type="button" class="btn btn-dark" style="width: 200px">
          Venue Management
        </button>
      </a>
    </div>
    <div class="row">
      <a href="{{url_for('views.add_movie')}}" class="col-md-4 mb-4">
        <button type="button" class="btn btn-dark" style="width: 200px">
          Add New Movie
        </button>
      </a>
      <a href="{{url_for('views.add_show')}}" class="col-md-4 mb-4">
        <button type="button" class="btn btn-dark" style="width: 200px">
          Add New Show
        </button>
      </a>
      <a href="{{url_for('views.add_venue')}}" class="col-md-4 mb-4">
        <button type="button" class="btn btn-dark" style="width: 200px">
          Add New Venue
        </button>
      </a>
    </div>
  </div>
  <h1>Theater Input Form</h1>
  <form action="/admin/add_venue" method="POST" enctype="multipart/form-data">
    <div class="form-group">
      <label for="name">Name:</label>
      <input type="text" class="form-control" id="name" name="name" required />
    </div>
    <div class="form-group">
      <label for="place">Place:</label>
      <input
        type="text"
        class="form-control"
        id="place"
        name="place"
        required
      />
    </div>
    <div class="form-group">
      <label for="capacity">Capacity:</label>
      <input
        type="number"
        class="form-control"
        id="capacity"
        name="capacity"
        required
      />
    </div>
    <div class="form-group">
      <label for="rph">RPH:</label>
      <input type="number" class="form-control" id="rph" name="rph" />
    </div>
    <div class="form-group">
      <label for="rating">Rating:</label>
      <input type="number" class="form-control" id="rating" name="rating" />
    </div>
    <div class="form-group">
      <label for="capacity_pre">Capacity Pre:</label>
      <input
        type="number"
        class="form-control"
        id="capacity_pre"
        name="capacity_pre"
      />
    </div>
    <div class="form-group">
      <label for="base_price">Base Price:</label>
      <input
        type="number"
        class="form-control"
        id="base_price"
        name="base_price"
      />
    </div>
    <div class="form-group">
      <label for="image">Add Image:</label>
      <input type="file" class="form-control" name="file" />
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock %}

application/templates/movies.html
{% extends 'base.html' %} {% block body %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li
      data-target="#carouselExampleIndicators"
      data-slide-to="0"
      class="active"
    ></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="static\1920_400.jpg" alt="First slide" />
    </div>
    <div class="carousel-item">
      <img
        class="d-block w-100"
        src="static\1920_400 (1).jpg"
        alt="Second slide"
      />
    </div>
    <div class="carousel-item">
      <img
        class="d-block w-100"
        src="static\1920_400 (2).jpg"
        alt="Third slide"
      />
    </div>
  </div>
  <a
    class="carousel-control-prev"
    href="#carouselExampleIndicators"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#carouselExampleIndicators"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="px-3 py-2">
  <h1 class="trending_title">Movies</h1>
  <form method="POST" action="/movies" class="d-flex justify-content-end">
    <div class="row">
      <div class="col-md-3 mb-3">
        <select class="form-select" id="tag" name="tag">
          <option value="None">Select Category</option>
          {% set tags = [] %} {% for movie in movies %} {% if movie.tags not in
          tags %}
          <option value="{{ movie.tags }}">{{ movie.tags }}</option>
          {% set _ = tags.append(movie.tags) %} {% endif %} {% endfor %}
        </select>
      </div>

      <div class="col-md-3 mb-3">
        <div class="form-check form-switch">
          <input
            class="form-check-input"
            type="checkbox"
            name="sort_by_rating"
            value="True"
            id="flexSwitchCheckDefault"
          />
          <label
            class="form-check-label d-inline-block"
            for="flexSwitchCheckDefault"
            >Sort by rating</label
          >
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <button type="submit" class="btn btn-primary">Apply</button>
      </div>

      <div class="col-md-3 mb-3">
        <a href="{{url_for('views.movies')}}">
          <button type="button" class="btn btn-danger" style="margin-top: 1%">
            Remove Filters
          </button>
        </a>
      </div>
    </div>
  </form>

  {% for movie in movies %}
  <div class="card mb-3">
    <img
      class="card-img-top"
      src="{{ url_for('static', filename=movie.filename) }}"
      alt="Movie Poster"
      width="1920"
      height="300"
    />
    <div class="card-body">
      <h5 class="card-title">{{ movie.name }}</h5>
      <p class="card-text">{{ movie.desc }}</p>
      <p class="card-text">
        <small class="text-muted">{{ movie.date }}</small><br />
        <small class="text-muted">{{ movie.tags }}</small>
      </p>

      <div class="d-flex flex-row">
        {% set n=movie.rating %} {% for i in range(n) %}
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="36"
          height="36"
          viewBox="0 0 24 24"
          style="fill: rgba(255, 215, 0, 1); transform: ; msfilter: "
        >
          <path
            d="M21.947 9.179a1.001 1.001 0 0 0-.868-.676l-5.701-.453-2.467-5.461a.998.998 0 0 0-1.822-.001L8.622 8.05l-5.701.453a1 1 0 0 0-.619 1.713l4.213 4.107-1.49 6.452a1 1 0 0 0 1.53 1.057L12 18.202l5.445 3.63a1.001 1.001 0 0 0 1.517-1.106l-1.829-6.4 4.536-4.082c.297-.268.406-.686.278-1.065z"
          ></path>
        </svg>
        {% endfor %}
      </div>
      <button
        type="button"
        class="btn btn-primary"
        style="margin-top: 1%"
        onclick="window.location.href='book/movie/{{movie.id}}'"
      >
        Book Now
      </button>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

application/templates/shows.html
{% extends 'base.html' %} {% block body %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li
      data-target="#carouselExampleIndicators"
      data-slide-to="0"
      class="active"
    ></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="static\1920_400.jpg" alt="First slide" />
    </div>
    <div class="carousel-item">
      <img
        class="d-block w-100"
        src="static\1920_400 (1).jpg"
        alt="Second slide"
      />
    </div>
    <div class="carousel-item">
      <img
        class="d-block w-100"
        src="static\1920_400 (2).jpg"
        alt="Third slide"
      />
    </div>
  </div>
  <a
    class="carousel-control-prev"
    href="#carouselExampleIndicators"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#carouselExampleIndicators"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="px-3 py-2">
  <h1 class="trending_title">Shows</h1>

  <form method="POST" action="/shows" class="d-flex justify-content-end">
    <div class="row">
      <div class="col-md-3 mb-3">
        <select class="form-select" id="tag" name="tag">
          <option value="None">Select Category</option>
          {% set tags = [] %} {% for show in shows %} {% if show.tags not in
          tags %}
          <option value="{{ show.tags }}">{{ show.tags }}</option>
          {% set _ = tags.append(show.tags) %} {% endif %} {% endfor %}
        </select>
      </div>

      <div class="col-md-3 mb-3">
        <div class="form-check form-switch">
          <input
            class="form-check-input"
            type="checkbox"
            name="sort_by_rating"
            value="True"
            id="flexSwitchCheckDefault"
          />
          <label
            class="form-check-label d-inline-block"
            for="flexSwitchCheckDefault"
            >Sort by rating</label
          >
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <button type="submit" class="btn btn-primary">Apply</button>
      </div>

      <div class="col-md-3 mb-3">
        <a href="{{url_for('views.shows')}}">
          <button type="button" class="btn btn-danger" style="margin-top: 1%">
            Remove Filters
          </button>
        </a>
      </div>
    </div>
  </form>

  {% for show in shows %}
  <div class="card mb-3">
    <img
      class="card-img-top"
      src="{{ url_for('static', filename=show.filename) }}"
      alt="Show Poster"
      width="1920"
      height="300"
    />
    <div class="card-body">
      <h5 class="card-title">{{ show.name }}</h5>
      <p class="card-text">{{ show.about }}</p>
      <p class="card-text">
        <small class="text-muted">{{ show.duration }} Minutes</small>
        <br />
        <small class="text-muted">{{ show.tags }} </small>
      </p>
      <div class="d-flex flex-row">
        {% set n=show.rating %} {% for i in range(n) %}
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="36"
          height="36"
          viewBox="0 0 24 24"
          style="fill: rgba(255, 215, 0, 1); transform: ; msfilter: "
        >
          <path
            d="M21.947 9.179a1.001 1.001 0 0 0-.868-.676l-5.701-.453-2.467-5.461a.998.998 0 0 0-1.822-.001L8.622 8.05l-5.701.453a1 1 0 0 0-.619 1.713l4.213 4.107-1.49 6.452a1 1 0 0 0 1.53 1.057L12 18.202l5.445 3.63a1.001 1.001 0 0 0 1.517-1.106l-1.829-6.4 4.536-4.082c.297-.268.406-.686.278-1.065z"
          ></path>
        </svg>
        {% endfor %}
      </div>
      <button
        type="button"
        class="btn btn-primary"
        style="margin-top: 1%"
        onclick="window.location.href='book/show/{{show.id}}'"
      >
        Book Now
      </button>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

application/templates/test.html
{% extends 'base.html' %} {% block body %} {{movies}}

<div style="width: 90%; margin: 0 auto">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Description</th>
        <th>Rating</th>
        <th>Release Date</th>
        <th>Theaters</th>
      </tr>
    </thead>
    <tbody>
      {% for movie in movies %}
      <tr>
        <td>{{ movie.id }}</td>
        <td>{{ movie.name }}</td>
        <td>{{ movie.desc}}</td>
        <td>{{ movie.rating}}</td>
        <td>{{ movie.date}}</td>
        <td>{{ movie.theaters }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% endblock %}
</div>

application/templates/venues.html
{% extends 'base.html' %} {% block body %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li
      data-target="#carouselExampleIndicators"
      data-slide-to="0"
      class="active"
    ></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="static\1920_400.jpg" alt="First slide" />
    </div>
    <div class="carousel-item">
      <img
        class="d-block w-100"
        src="static\1920_400 (1).jpg"
        alt="Second slide"
      />
    </div>
    <div class="carousel-item">
      <img
        class="d-block w-100"
        src="static\1920_400 (2).jpg"
        alt="Third slide"
      />
    </div>
  </div>
  <a
    class="carousel-control-prev"
    href="#carouselExampleIndicators"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#carouselExampleIndicators"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="px-3 py-2">
  <h1 class="trending_title">Venues</h1>
  <div class="card-horizontal mx-auto">
    <form method="POST" action="/venues" class="d-flex justify-content-end">
      <div class="row">
        <div class="col-md-3 mb-3">
          <select class="form-select" id="tag" name="tag">
            <option value="None">Select City</option>
            {% set places = [] %} {% for venue in venues %} {% if venue.place
            not in places %}
            <option value="{{ venue.place }}">{{ venue.place }}</option>
            {% set _ = places.append(venue.place) %} {% endif %} {% endfor %}
          </select>
        </div>

        <div class="col-md-3 mb-3">
          <div class="form-check form-switch">
            <input
              class="form-check-input"
              type="checkbox"
              name="sort_by_rating"
              value="True"
              id="flexSwitchCheckDefault"
            />
            <label
              class="form-check-label d-inline-block"
              for="flexSwitchCheckDefault"
              >Sort by rating</label
            >
          </div>
        </div>

        <div class="col-md-3 mb-3">
          <button type="submit" class="btn btn-primary">Apply</button>
        </div>

        <div class="col-md-3 mb-3">
          <a href="{{url_for('views.venues')}}">
            <button type="button" class="btn btn-danger" style="margin-top: 1%">
              Remove Filters
            </button>
          </a>
        </div>
      </div>
    </form>
  </div>
  {% for venue in venues %}
  <div class="card mb-3">
    <img
      class="card-img-top"
      src="{{ url_for('static', filename=venue.filename) }}"
      alt="Image of Venue"
      width="1920"
      height="300"
    />
    <div class="card-body">
      <h5 class="card-title">{{venue.name}}</h5>
      <p class="card-text">
        Capacity: {{venue.capacity}} <br />
        Base Price: {{venue.base_price}}
      </p>
      <p class="card-text">
        <small class="text-muted">{{venue.place}}</small>
      </p>
      <div class="d-flex flex-row">
        {% set n=venue.rating %} {% for i in range(n) %}
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="36"
          height="36"
          viewBox="0 0 24 24"
          style="fill: rgba(255, 215, 0, 1); transform: ; msfilter: "
        >
          <path
            d="M21.947 9.179a1.001 1.001 0 0 0-.868-.676l-5.701-.453-2.467-5.461a.998.998 0 0 0-1.822-.001L8.622 8.05l-5.701.453a1 1 0 0 0-.619 1.713l4.213 4.107-1.49 6.452a1 1 0 0 0 1.53 1.057L12 18.202l5.445 3.63a1.001 1.001 0 0 0 1.517-1.106l-1.829-6.4 4.536-4.082c.297-.268.406-.686.278-1.065z"
          ></path>
        </svg>
        {% endfor %}
      </div>
      <button
        type="button"
        class="btn btn-primary"
        style="margin-top: 1%"
        onclick="window.location.href='book/venue/{{venue.id}}'"
      >
        Book Now
      </button>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}